spring:
  data:
    mongodb:
      #uri: mongodb://root:root@192.168.8.128:27017/test
      host: 192.168.8.128
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: test






































