##thymelea
spring:
  messages:
    basename: msg/home
    encoding: UTF-8
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html


